name: XSCasino
version: '${project.version}'
main: net.xsapi.panat.xscasino.core.XSCasino
api-version: 1.20
softdepend: [ Vault ]
commands:
  xscasino:
    description: "Main Command"
    aliases:
      - casino